const flashcards = [
  { "chinese": "安静", "pinyin": "ānjìng", "vietnamese": "yên tĩnh, trầm lặng", "example": "请安静，图书馆里不准大声说话。", "example_vi": "Xin hãy yên lặng, trong thư viện không được phép nói chuyện lớn tiếng." },
  { "chinese": "把", "pinyin": "bǎ", "vietnamese": "dùng để đưa tân ngữ lên trước động từ", "example": "请把这本书给我。", "example_vi": "Làm ơn đưa cuốn sách này cho tôi." },
  { "chinese": "班", "pinyin": "bān", "vietnamese": "lớp học, ca làm", "example": "我们班有二十个学生。", "example_vi": "Lớp chúng tôi có hai mươi học sinh." },
  { "chinese": "搬", "pinyin": "bān", "vietnamese": "dọn, chuyển (đồ, nhà)", "example": "我下个星期要搬家。", "example_vi": "Tuần tới tôi phải chuyển nhà." },
  { "chinese": "办法", "pinyin": "bànfǎ", "vietnamese": "cách, biện pháp", "example": "你有什么好办法吗？", "example_vi": "Bạn có cách nào hay không?" },
  { "chinese": "办公室", "pinyin": "bàngōngshì", "vietnamese": "văn phòng", "example": "经理在办公室里等你。", "example_vi": "Giám đốc đang đợi bạn trong văn phòng." },
  { "chinese": "半", "pinyin": "bàn", "vietnamese": "nửa", "example": "现在是三点半。", "example_vi": "Bây giờ là ba giờ rưỡi." },
  { "chinese": "帮忙", "pinyin": "bāngmáng", "vietnamese": "giúp, giúp đỡ", "example": "你能帮我一个忙吗？", "example_vi": "Bạn có thể giúp tôi một việc được không?" },
  { "chinese": "包", "pinyin": "bāo", "vietnamese": "túi, bao", "example": "我的包是黑色的。", "example_vi": "Túi của tôi màu đen." },
  { "chinese": "饱", "pinyin": "bǎo", "vietnamese": "no, đầy bụng", "example": "我吃饱了，谢谢。", "example_vi": "Tôi no rồi, cảm ơn." },
  { "chinese": "北方", "pinyin": "běifāng", "vietnamese": "miền Bắc", "example": "北方的冬天很冷。", "example_vi": "Mùa đông ở miền Bắc rất lạnh." },
  { "chinese": "被", "pinyin": "bèi", "vietnamese": "bị (dùng trong câu bị động)", "example": "我的钱包被偷了。", "example_vi": "Ví tiền của tôi đã bị trộm mất." },
  { "chinese": "鼻子", "pinyin": "bízi", "vietnamese": "mũi", "example": "他的鼻子很高。", "example_vi": "Mũi của anh ấy rất cao." },
  { "chinese": "比较", "pinyin": "bǐjiào", "vietnamese": "khá, tương đối", "example": "今天的天气比较好。", "example_vi": "Thời tiết hôm nay khá tốt." },
  { "chinese": "比赛", "pinyin": "bǐsài", "vietnamese": "thi đấu, cuộc thi", "example": "你看了昨天的足球比赛吗？", "example_vi": "Bạn đã xem trận đấu bóng đá ngày hôm qua chưa?" },
  { "chinese": "笔记本", "pinyin": "bǐjìběn", "vietnamese": "sổ ghi chép, laptop", "example": "我忘带笔记本了。", "example_vi": "Tôi quên mang sổ tay rồi." },
  { "chinese": "必须", "pinyin": "bìxū", "vietnamese": "phải, bắt buộc", "example": "你必须按时完成作业。", "example_vi": "Bạn phải hoàn thành bài tập đúng giờ." },
  { "chinese": "变化", "pinyin": "biànhuà", "vietnamese": "thay đổi", "example": "这个城市的变化很大。", "example_vi": "Sự thay đổi của thành phố này rất lớn." },
  { "chinese": "别人", "pinyin": "biéren", "vietnamese": "người khác", "example": "不要在背后说别人的坏话。", "example_vi": "Đừng nói xấu người khác sau lưng." },
  { "chinese": "冰箱", "pinyin": "bīngxiāng", "vietnamese": "tủ lạnh", "example": "冰箱里还有牛奶吗？", "example_vi": "Trong tủ lạnh còn sữa không?" },
  { "chinese": "不但...而且...", "pinyin": "bùdàn... érqiě...", "vietnamese": "không những... mà còn...", "example": "他不但会说英语，而且还会说法语。", "example_vi": "Anh ấy không những biết nói tiếng Anh mà còn biết nói tiếng Pháp." },
  { "chinese": "菜单", "pinyin": "càidān", "vietnamese": "thực đơn", "example": "服务员，请给我菜单。", "example_vi": "Phục vụ, cho tôi xin thực đơn." },
  { "chinese": "参加", "pinyin": "cānjiā", "vietnamese": "tham gia", "example": "我想参加这个活动。", "example_vi": "Tôi muốn tham gia hoạt động này." },
  { "chinese": "草", "pinyin": "cǎo", "vietnamese": "cỏ", "example": "公园里有很多绿色的草。", "example_vi": "Trong công viên có rất nhiều cỏ xanh." },
  { "chinese": "层", "pinyin": "céng", "vietnamese": "tầng (nhà)", "example": "我住在三层。", "example_vi": "Tôi sống ở tầng ba." },
  { "chinese": "差", "pinyin": "chà", "vietnamese": "thiếu, kém", "example": "我的数学成绩很差。", "example_vi": "Thành tích môn toán của tôi rất kém." },
  { "chinese": "超市", "pinyin": "chāoshì", "vietnamese": "siêu thị", "example": "我们去超市买点东西吧。", "example_vi": "Chúng ta đi siêu thị mua chút đồ đi." },
  { "chinese": "衬衫", "pinyin": "chènshān", "vietnamese": "áo sơ mi", "example": "他今天穿了一件白衬衫。", "example_vi": "Hôm nay anh ấy mặc một chiếc áo sơ mi trắng." },
  { "chinese": "成绩", "pinyin": "chéngjì", "vietnamese": "thành tích, kết quả", "example": "这次考试我的成绩很好。", "example_vi": "Kết quả bài kiểm tra lần này của tôi rất tốt." },
  { "chinese": "城市", "pinyin": "chéngshì", "vietnamese": "thành phố", "example": "北京是一个大城市。", "example_vi": "Bắc Kinh là một thành phố lớn." },
  { "chinese": "迟到", "pinyin": "chídào", "vietnamese": "đến muộn", "example": "对不起，我今天迟到了。", "example_vi": "Xin lỗi, hôm nay tôi đến muộn." },
  { "chinese": "出现", "pinyin": "chūxiàn", "vietnamese": "xuất hiện", "example": "问题终于出现了。", "example_vi": "Vấn đề cuối cùng cũng đã xuất hiện." },
  { "chinese": "厨房", "pinyin": "chúfáng", "vietnamese": "nhà bếp", "example": "妈妈正在厨房做饭。", "example_vi": "Mẹ đang nấu ăn trong bếp." },
  { "chinese": "除了", "pinyin": "chúle", "vietnamese": "ngoài ra, trừ", "example": "除了苹果，别的我都不喜欢吃。", "example_vi": "Ngoài táo ra, tôi không thích ăn thứ gì khác." },
  { "chinese": "春", "pinyin": "chūn", "vietnamese": "mùa xuân", "example": "春天来了，花都开了。", "example_vi": "Mùa xuân đến rồi, hoa đã nở." },
  { "chinese": "词语", "pinyin": "cíyǔ", "vietnamese": "từ vựng", "example": "这个词语是什么意思？", "example_vi": "Từ này có nghĩa là gì?" },
  { "chinese": "聪明", "pinyin": "cōngming", "vietnamese": "thông minh", "example": "他是一个非常聪明的孩子。", "example_vi": "Cậu bé ấy là một đứa trẻ rất thông minh." },
  { "chinese": "打扫", "pinyin": "dǎsǎo", "vietnamese": "quét dọn", "example": "我每个周末都打扫房间。", "example_vi": "Tôi dọn dẹp phòng mỗi cuối tuần." },
  { "chinese": "打算", "pinyin": "dǎsuàn", "vietnamese": "dự định", "example": "你明天有什么打算？", "example_vi": "Ngày mai bạn có dự định gì không?" },
  { "chinese": "带", "pinyin": "dài", "vietnamese": "mang theo", "example": "出门别忘了带伞。", "example_vi": "Ra ngoài đừng quên mang ô." },
  { "chinese": "担心", "pinyin": "dānxīn", "vietnamese": "lo lắng", "example": "别担心，一切都会好的。", "example_vi": "Đừng lo lắng, mọi chuyện rồi sẽ ổn thôi." },
  { "chinese": "蛋糕", "pinyin": "dàngāo", "vietnamese": "bánh ngọt", "example": "生日快乐！这是你的蛋糕。", "example_vi": "Chúc mừng sinh nhật! Đây là bánh của bạn." },
  { "chinese": "当然", "pinyin": "dāngrán", "vietnamese": "dĩ nhiên", "example": "你当然可以来参加我的派对。", "example_vi": "Tất nhiên bạn có thể đến tham dự bữa tiệc của tôi." },
  { "chinese": "灯", "pinyin": "dēng", "vietnamese": "đèn", "example": "请把灯打开。", "example_vi": "Làm ơn bật đèn lên." },
  { "chinese": "低", "pinyin": "dī", "vietnamese": "thấp", "example": "这个桌子太低了。", "example_vi": "Cái bàn này thấp quá." },
  { "chinese": "地铁", "pinyin": "dìtiě", "vietnamese": "tàu điện ngầm", "example": "我每天坐地铁上班。", "example_vi": "Tôi đi làm bằng tàu điện ngầm mỗi ngày." },
  { "chinese": "地图", "pinyin": "dìtú", "vietnamese": "bản đồ", "example": "你看一下地图，我们现在在哪里？", "example_vi": "Bạn xem bản đồ một chút, chúng ta đang ở đâu?" },
  { "chinese": "电梯", "pinyin": "diàntī", "vietnamese": "thang máy", "example": "我们坐电梯上去吧。", "example_vi": "Chúng ta đi thang máy lên đi." },
  { "chinese": "电子邮件", "pinyin": "diànzǐ yóujiàn", "vietnamese": "thư điện tử, email", "example": "我刚刚给你发了一封电子邮件。", "example_vi": "Tôi vừa mới gửi cho bạn một email." },
  { "chinese": "东", "pinyin": "dōng", "vietnamese": "hướng Đông", "example": "太阳从东边升起。", "example_vi": "Mặt trời mọc ở hướng đông." },
  { "chinese": "冬", "pinyin": "dōng", "vietnamese": "mùa đông", "example": "冬天很冷，要多穿衣服。", "example_vi": "Mùa đông rất lạnh, cần phải mặc nhiều quần áo." },
  { "chinese": "动物", "pinyin": "dòngwù", "vietnamese": "động vật", "example": "我喜欢去动物园看动物。", "example_vi": "Tôi thích đến sở thú xem động vật." },
  { "chinese": "短", "pinyin": "duǎn", "vietnamese": "ngắn", "example": "这条裤子太短了。", "example_vi": "Cái quần này ngắn quá." },
  { "chinese": "段", "pinyin": "duàn", "vietnamese": "đoạn, quãng", "example": "这段时间我很忙。", "example_vi": "Khoảng thời gian này tôi rất bận." },
  { "chinese": "锻炼", "pinyin": "duànliàn", "vietnamese": "rèn luyện (thể dục)", "example": "我们应该每天锻炼身体。", "example_vi": "Chúng ta nên tập thể dục mỗi ngày." },
  { "chinese": "多么", "pinyin": "duōme", "vietnamese": "biết bao, thật là", "example": "这里的风景多么美啊！", "example_vi": "Phong cảnh ở đây đẹp biết bao!" },
  { "chinese": "饿", "pinyin": "è", "vietnamese": "đói", "example": "我饿了，想吃点东西。", "example_vi": "Tôi đói rồi, muốn ăn chút gì đó." },
  { "chinese": "耳朵", "pinyin": "ěrduo", "vietnamese": "tai", "example": "我的耳朵有点疼。", "example_vi": "Tai của tôi hơi đau." },
  { "chinese": "发", "pinyin": "fā", "vietnamese": "gửi, phát (tin nhắn, thư)", "example": "你给我发短信了吗？", "example_vi": "Bạn có gửi tin nhắn cho tôi không?" },
  { "chinese": "发现", "pinyin": "fāxiàn", "vietnamese": "phát hiện", "example": "我发现了一个秘密。", "example_vi": "Tôi đã phát hiện ra một bí mật." },
  { "chinese": "方便", "pinyin": "fāngbiàn", "vietnamese": "thuận tiện", "example": "这里交通很方便。", "example_vi": "Giao thông ở đây rất thuận tiện." },
  { "chinese": "放", "pinyin": "fàng", "vietnamese": "đặt, để, thả", "example": "请把书放在桌子上。", "example_vi": "Làm ơn đặt sách lên bàn." },
  { "chinese": "放心", "pinyin": "fàngxīn", "vietnamese": "yên tâm", "example": "你放心吧，我会照顾好自己的。", "example_vi": "Bạn yên tâm đi, tôi sẽ tự chăm sóc tốt cho bản thân." },
  { "chinese": "分", "pinyin": "fēn", "vietnamese": "phút, điểm, phân", "example": "现在是八点十分。", "example_vi": "Bây giờ là tám giờ mười phút." },
  { "chinese": "附近", "pinyin": "fùjìn", "vietnamese": "gần đây", "example": "这附近有银行吗？", "example_vi": "Gần đây có ngân hàng không?" },
  { "chinese": "复习", "pinyin": "fùxí", "vietnamese": "ôn tập", "example": "考试前要好好复习。", "example_vi": "Trước kỳ thi phải ôn tập thật kỹ." },
  { "chinese": "干净", "pinyin": "gānjìng", "vietnamese": "sạch sẽ", "example": "你的房间真干净！", "example_vi": "Phòng của bạn thật sạch sẽ!" },
  { "chinese": "感冒", "pinyin": "gǎnmào", "vietnamese": "cảm lạnh", "example": "我好像感冒了。", "example_vi": "Tôi hình như bị cảm rồi." },
  { "chinese": "感兴趣", "pinyin": "gǎn xìngqù", "vietnamese": "hứng thú", "example": "我对中国历史很感兴趣。", "example_vi": "Tôi rất có hứng thú với lịch sử Trung Quốc." },
  { "chinese": "刚才", "pinyin": "gāngcái", "vietnamese": "vừa nãy", "example": "刚才谁来过了？", "example_vi": "Vừa nãy ai đã đến vậy?" },
  { "chinese": "个子", "pinyin": "gèzi", "vietnamese": "vóc dáng, chiều cao", "example": "他个子很高。", "example_vi": "Anh ấy rất cao." },
  { "chinese": "根据", "pinyin": "gēnjù", "vietnamese": "căn cứ theo", "example": "根据天气预报，明天会下雨。", "example_vi": "Theo dự báo thời tiết, ngày mai trời sẽ mưa." },
  { "chinese": "更", "pinyin": "gèng", "vietnamese": "càng, hơn", "example": "这个比那个更好。", "example_vi": "Cái này tốt hơn cái kia." },
  { "chinese": "公园", "pinyin": "gōngyuán", "vietnamese": "công viên", "example": "我们下午去公园散步吧。", "example_vi": "Chiều nay chúng ta đi dạo công viên đi." },
  { "chinese": "故事", "pinyin": "gùshi", "vietnamese": "câu chuyện", "example": "睡觉前，妈妈给我讲故事。", "example_vi": "Trước khi đi ngủ, mẹ kể chuyện cho tôi nghe." },
  { "chinese": "刮风", "pinyin": "guā fēng", "vietnamese": "gió thổi", "example": "外面在刮风，别出去了。", "example_vi": "Bên ngoài đang có gió, đừng ra ngoài." },
  { "chinese": "关", "pinyin": "guān", "vietnamese": "tắt, đóng", "example": "请关门，谢谢。", "example_vi": "Làm ơn đóng cửa, cảm ơn." },
  { "chinese": "关系", "pinyin": "guānxì", "vietnamese": "quan hệ", "example": "他们俩是什么关系？", "example_vi": "Mối quan hệ của hai người họ là gì?" },
  { "chinese": "关心", "pinyin": "guānxīn", "vietnamese": "quan tâm", "example": "谢谢你的关心。", "example_vi": "Cảm ơn sự quan tâm của bạn." },
  { "chinese": "关于", "pinyin": "guānyú", "vietnamese": "về, liên quan đến", "example": "关于这个问题，我们明天再讨论。", "example_vi": "Về vấn đề này, ngày mai chúng ta sẽ thảo luận tiếp." },
  { "chinese": "国家", "pinyin": "guójiā", "vietnamese": "quốc gia", "example": "中国是一个美丽的国家。", "example_vi": "Trung Quốc là một đất nước xinh đẹp." },
  { "chinese": "过", "pinyin": "guò", "vietnamese": "từng (trải qua)", "example": "我吃过北京烤鸭。", "example_vi": "Tôi đã từng ăn vịt quay Bắc Kinh." },
  { "chinese": "过去", "pinyin": "guòqù", "vietnamese": "quá khứ, trước đây", "example": "过去的事情就让它过去吧。", "example_vi": "Chuyện đã qua thì hãy để nó qua đi." },
  { "chinese": "还是", "pinyin": "háishi", "vietnamese": "vẫn, hay là", "example": "你喝茶还是喝咖啡？", "example_vi": "Bạn uống trà hay uống cà phê?" },
  { "chinese": "害怕", "pinyin": "hàipà", "vietnamese": "sợ", "example": "我害怕一个人在家。", "example_vi": "Tôi sợ ở nhà một mình." },
  { "chinese": "黑板", "pinyin": "hēibǎn", "vietnamese": "bảng đen", "example": "老师在黑板上写字。", "example_vi": "Thầy giáo đang viết chữ trên bảng đen." },
  { "chinese": "护照", "pinyin": "hùzhào", "vietnamese": "hộ chiếu", "example": "出国旅行需要带护照。", "example_vi": "Đi du lịch nước ngoài cần mang theo hộ chiếu." },
  { "chinese": "花", "pinyin": "huā", "vietnamese": "hoa; tiêu (tiền, thời gian)", "example": "这个月我花了很多钱。", "example_vi": "Tháng này tôi đã tiêu rất nhiều tiền." },
  { "chinese": "画", "pinyin": "huà", "vietnamese": "vẽ, tranh vẽ", "example": "她画的画很漂亮。", "example_vi": "Bức tranh cô ấy vẽ rất đẹp." },
  { "chinese": "坏", "pinyin": "huài", "vietnamese": "hỏng, xấu", "example": "我的手机坏了。", "example_vi": "Điện thoại của tôi bị hỏng rồi." },
  { "chinese": "环境", "pinyin": "huánjìng", "vietnamese": "môi trường", "example": "我们要注意保护环境。", "example_vi": "Chúng ta phải chú ý bảo vệ môi trường." },
  { "chinese": "会议", "pinyin": "huìyì", "vietnamese": "cuộc họp", "example": "明天上午九点有一个会议。", "example_vi": "Sáng mai lúc chín giờ có một cuộc họp." },
  { "chinese": "或者", "pinyin": "huòzhě", "vietnamese": "hoặc là", "example": "我们可以去看电影或者去逛街。", "example_vi": "Chúng ta có thể đi xem phim hoặc đi dạo phố." },
  { "chinese": "几乎", "pinyin": "jīhū", "vietnamese": "hầu như", "example": "我几乎忘了这件事。", "example_vi": "Tôi gần như đã quên mất chuyện này." },
  { "chinese": "机会", "pinyin": "jīhuì", "vietnamese": "cơ hội", "example": "这是一个很好的机会。", "example_vi": "Đây là một cơ hội rất tốt." },
  { "chinese": "记得", "pinyin": "jìde", "vietnamese": "nhớ", "example": "你还记得我吗？", "example_vi": "Bạn còn nhớ tôi không?" },
  { "chinese": "检查", "pinyin": "jiǎnchá", "vietnamese": "kiểm tra", "example": "医生正在给病人检查身体。", "example_vi": "Bác sĩ đang kiểm tra sức khỏe cho bệnh nhân." },
  { "chinese": "简单", "pinyin": "jiǎndān", "vietnamese": "đơn giản", "example": "这个问题很简单。", "example_vi": "Vấn đề này rất đơn giản." },
  { "chinese": "健康", "pinyin": "jiànkāng", "vietnamese": "khỏe mạnh", "example": "健康是最重要的。", "example_vi": "Sức khỏe là quan trọng nhất." },
  { "chinese": "见面", "pinyin": "jiàn miàn", "vietnamese": "gặp mặt", "example": "我们明天在哪里见面？", "example_vi": "Ngày mai chúng ta gặp nhau ở đâu?" },
  { "chinese": "教", "pinyin": "jiāo", "vietnamese": "dạy", "example": "王老师教我们数学。", "example_vi": "Thầy Vương dạy chúng tôi môn toán." },
  { "chinese": "脚", "pinyin": "jiǎo", "vietnamese": "chân", "example": "我的脚受伤了。", "example_vi": "Chân của tôi bị thương rồi." },
  { "chinese": "角", "pinyin": "jiǎo", "vietnamese": "góc; tiền xu (0.1 nhân dân tệ)", "example": "这个苹果五角钱。", "example_vi": "Quả táo này giá 5 hào." },
  { "chinese": "接", "pinyin": "jiē", "vietnamese": "đón, nhận", "example": "我去机场接你。", "example_vi": "Tôi ra sân bay đón bạn." },
  { "chinese": "街道", "pinyin": "jiēdào", "vietnamese": "con đường, khu phố", "example": "这条街道很热闹。", "example_vi": "Con phố này rất náo nhiệt." },
  { "chinese": "结婚", "pinyin": "jiéhūn", "vietnamese": "kết hôn", "example": "他们下个月就要结婚了。", "example_vi": "Tháng sau họ sẽ kết hôn." },
  { "chinese": "节目", "pinyin": "jiémù", "vietnamese": "tiết mục", "example": "今天的晚会节目很精彩。", "example_vi": "Tiết mục của buổi tiệc tối nay rất đặc sắc." },
  { "chinese": "节日", "pinyin": "jiérì", "vietnamese": "ngày lễ", "example": "春节是中国最重要的节日。", "example_vi": "Tết Nguyên Đán là ngày lễ quan trọng nhất của Trung Quốc." },
  { "chinese": "解决", "pinyin": "jiějué", "vietnamese": "giải quyết", "example": "我们必须想办法解决这个问题。", "example_vi": "Chúng ta phải tìm cách giải quyết vấn đề này." },
  { "chinese": "借", "pinyin": "jiè", "vietnamese": "mượn, cho mượn", "example": "我可以借你的笔用一下吗？", "example_vi": "Tôi có thể mượn bút của bạn một chút được không?" },
  { "chinese": "经常", "pinyin": "jīngcháng", "vietnamese": "thường xuyên", "example": "我经常去那家咖啡馆。", "example_vi": "Tôi thường xuyên đến quán cà phê đó." },
  { "chinese": "经过", "pinyin": "jīngguò", "vietnamese": "đi qua; trải qua", "example": "我每天上学都经过这个公园。", "example_vi": "Mỗi ngày đi học tôi đều đi qua công viên này." },
  { "chinese": "经理", "pinyin": "jīnglǐ", "vietnamese": "giám đốc", "example": "他是我们公司的经理。", "example_vi": "Anh ấy là giám đốc của công ty chúng tôi." },
  { "chinese": "久", "pinyin": "jiǔ", "vietnamese": "lâu", "example": "好久不见，你最近怎么样？", "example_vi": "Lâu rồi không gặp, dạo này bạn thế nào?" },
  { "chinese": "旧", "pinyin": "jiù", "vietnamese": "cũ", "example": "这件衣服太旧了。", "example_vi": "Bộ quần áo này cũ quá rồi." },
  { "chinese": "举行", "pinyin": "jǔxíng", "vietnamese": "tổ chức", "example": "学校将举行运动会。", "example_vi": "Nhà trường sẽ tổ chức hội thao." },
  { "chinese": "句子", "pinyin": "jùzi", "vietnamese": "câu", "example": "请用这个词造一个句子。", "example_vi": "Hãy dùng từ này để đặt một câu." },
  { "chinese": "决定", "pinyin": "juédìng", "vietnamese": "quyết định", "example": "我决定明天去旅行。", "example_vi": "Tôi quyết định ngày mai sẽ đi du lịch." },
  { "chinese": "可爱", "pinyin": "kě’ài", "vietnamese": "dễ thương", "example": "这只小猫真可爱。", "example_vi": "Con mèo con này thật dễ thương." },
  { "chinese": "渴", "pinyin": "kě", "vietnamese": "khát", "example": "我很渴，想喝水。", "example_vi": "Tôi rất khát, muốn uống nước." },
  { "chinese": "刻", "pinyin": "kè", "vietnamese": "khắc; 15 phút", "example": "现在是三点一刻。", "example_vi": "Bây giờ là ba giờ mười lăm phút." },
  { "chinese": "客人", "pinyin": "kèrén", "vietnamese": "khách", "example": "家里来了很多客人。", "example_vi": "Nhà có rất nhiều khách." },
  { "chinese": "空调", "pinyin": "kōngtiáo", "vietnamese": "máy điều hòa", "example": "天气太热了，快开空调吧。", "example_vi": "Thời tiết nóng quá, mau bật điều hòa lên." },
  { "chinese": "口", "pinyin": "kǒu", "vietnamese": "miệng; lượng từ cho người trong gia đình", "example": "我们家有三口人。", "example_vi": "Nhà chúng tôi có ba người." },
  { "chinese": "哭", "pinyin": "kū", "vietnamese": "khóc", "example": "那个小女孩为什么哭？", "example_vi": "Tại sao cô bé đó lại khóc?" },
  { "chinese": "裤子", "pinyin": "kùzi", "vietnamese": "quần", "example": "我买了一条新裤子。", "example_vi": "Tôi đã mua một chiếc quần mới." },
  { "chinese": "筷子", "pinyin": "kuàizi", "vietnamese": "đũa", "example": "你会用筷子吗？", "example_vi": "Bạn có biết dùng đũa không?" },
  { "chinese": "蓝", "pinyin": "lán", "vietnamese": "màu xanh lam", "example": "天空是蓝色的。", "example_vi": "Bầu trời màu xanh lam." },
  { "chinese": "老", "pinyin": "lǎo", "vietnamese": "già, cũ", "example": "我的爷爷年纪老了。", "example_vi": "Ông nội tôi đã già rồi." },
  { "chinese": "离开", "pinyin": "líkāi", "vietnamese": "rời khỏi", "example": "他已经离开北京了。", "example_vi": "Anh ấy đã rời khỏi Bắc Kinh rồi." },
  { "chinese": "历史", "pinyin": "lìshǐ", "vietnamese": "lịch sử", "example": "我对中国历史很感兴趣。", "example_vi": "Tôi rất có hứng thú với lịch sử Trung Quốc." },
  { "chinese": "脸", "pinyin": "liǎn", "vietnamese": "mặt", "example": "她的脸红了。", "example_vi": "Mặt cô ấy đỏ lên rồi." },
  { "chinese": "练习", "pinyin": "liànxí", "vietnamese": "luyện tập", "example": "学好汉语要多练习。", "example_vi": "Để học tốt tiếng Trung cần phải luyện tập nhiều." },
  { "chinese": "辆", "pinyin": "liàng", "vietnamese": "chiếc (xe cộ)", "example": "门口停着一辆车。", "example_vi": "Trước cửa có một chiếc xe đang đỗ." },
  { "chinese": "聊天", "pinyin": "liáotiān", "vietnamese": "tán gẫu, nói chuyện", "example": "我喜欢和朋友聊天。", "example_vi": "Tôi thích nói chuyện phiếm với bạn bè." },
  { "chinese": "了解", "pinyin": "liǎojiě", "vietnamese": "hiểu biết", "example": "你了解他吗？", "example_vi": "Bạn có hiểu anh ấy không?" },
  { "chinese": "邻居", "pinyin": "línjū", "vietnamese": "hàng xóm", "example": "我的邻居很友好。", "example_vi": "Hàng xóm của tôi rất thân thiện." },
  { "chinese": "楼", "pinyin": "lóu", "vietnamese": "tầng, tòa nhà", "example": "这栋楼很高。", "example_vi": "Tòa nhà này rất cao." },
  { "chinese": "绿", "pinyin": "lǜ", "vietnamese": "màu xanh lá", "example": "我喜欢绿色的衣服。", "example_vi": "Tôi thích quần áo màu xanh lá." },
  { "chinese": "马", "pinyin": "mǎ", "vietnamese": "con ngựa", "example": "他骑着一匹白马。", "example_vi": "Anh ấy đang cưỡi một con ngựa trắng." },
  { "chinese": "马上", "pinyin": "mǎshàng", "vietnamese": "ngay lập tức", "example": "你等一下，我马上就来。", "example_vi": "Bạn đợi một chút, tôi đến ngay." },
  { "chinese": "满意", "pinyin": "mǎnyì", "vietnamese": "hài lòng", "example": "你对这个结果满意吗？", "example_vi": "Bạn có hài lòng với kết quả này không?" },
  { "chinese": "帽子", "pinyin": "màozi", "vietnamese": "mũ", "example": "外面风大，戴上帽子吧。", "example_vi": "Bên ngoài gió lớn, đội mũ vào đi." },
  { "chinese": "米", "pinyin": "mǐ", "vietnamese": "gạo; mét", "example": "他身高一米八。", "example_vi": "Anh ấy cao một mét tám." },
  { "chinese": "面包", "pinyin": "miànbāo", "vietnamese": "bánh mì", "example": "我早餐喜欢吃面包。", "example_vi": "Bữa sáng tôi thích ăn bánh mì." },
  { "chinese": "明白", "pinyin": "míngbai", "vietnamese": "hiểu, rõ ràng", "example": "你明白我的意思吗？", "example_vi": "Bạn có hiểu ý của tôi không?" },
  { "chinese": "拿", "pinyin": "ná", "vietnamese": "cầm, lấy", "example": "请帮我拿下那个杯子。", "example_vi": "Làm ơn lấy giúp tôi cái cốc kia." },
  { "chinese": "奶奶", "pinyin": "nǎinai", "vietnamese": "bà nội", "example": "我奶奶今年八十岁了。", "example_vi": "Bà nội tôi năm nay tám mươi tuổi." },
  { "chinese": "南", "pinyin": "nán", "vietnamese": "hướng Nam", "example": "我的家在城市的南边。", "example_vi": "Nhà tôi ở phía nam thành phố." },
  { "chinese": "难", "pinyin": "nán", "vietnamese": "khó", "example": "这个问题太难了。", "example_vi": "Vấn đề này khó quá." },
  { "chinese": "难过", "pinyin": "nánguò", "vietnamese": "buồn, khó chịu", "example": "听到这个消息，我很难过。", "example_vi": "Nghe được tin này, tôi rất buồn." },
  { "chinese": "年级", "pinyin": "niánjí", "vietnamese": "lớp (năm học)", "example": "我弟弟上小学二年级。", "example_vi": "Em trai tôi học lớp hai tiểu học." },
  { "chinese": "年轻", "pinyin": "niánqīng", "vietnamese": "trẻ", "example": "他看起来很年轻。", "example_vi": "Anh ấy trông rất trẻ." },
  { "chinese": "鸟", "pinyin": "niǎo", "vietnamese": "chim", "example": "树上有很多鸟在唱歌。", "example_vi": "Trên cây có rất nhiều con chim đang hót." },
  { "chinese": "努力", "pinyin": "nǔlì", "vietnamese": "nỗ lực, chăm chỉ", "example": "只要努力，就一定会成功。", "example_vi": "Chỉ cần nỗ lực, nhất định sẽ thành công." },
  { "chinese": "爬山", "pinyin": "pá shān", "vietnamese": "leo núi", "example": "我们周末去爬山吧。", "example_vi": "Cuối tuần chúng ta đi leo núi đi." },
  { "chinese": "盘子", "pinyin": "pánzi", "vietnamese": "cái đĩa", "example": "桌子上有一个盘子。", "example_vi": "Trên bàn có một cái đĩa." },
  { "chinese": "胖", "pinyin": "pàng", "vietnamese": "mập", "example": "他最近吃胖了。", "example_vi": "Dạo này anh ấy béo lên." },
  { "chinese": "啤酒", "pinyin": "píjiǔ", "vietnamese": "bia", "example": "夏天喝冰啤酒很舒服。", "example_vi": "Mùa hè uống bia lạnh rất thoải mái." },
  { "chinese": "葡萄", "pinyin": "pútáo", "vietnamese": "nho", "example": "我喜欢吃葡萄。", "example_vi": "Tôi thích ăn nho." },
  { "chinese": "普通话", "pinyin": "pǔtōnghuà", "vietnamese": "tiếng phổ thông", "example": "他的普通话说得很标准。", "example_vi": "Tiếng Phổ thông của anh ấy nói rất chuẩn." },
  { "chinese": "其实", "pinyin": "qíshí", "vietnamese": "thật ra", "example": "其实，我不太喜欢看电影。", "example_vi": "Thực ra, tôi không thích xem phim lắm." },
  { "chinese": "其他", "pinyin": "qítā", "vietnamese": "cái khác", "example": "除了他，其他人都来了。", "example_vi": "Ngoại trừ anh ấy, những người khác đều đã đến." },
  { "chinese": "奇怪", "pinyin": "qíguài", "vietnamese": "kỳ lạ", "example": "今天天气真奇怪。", "example_vi": "Thời tiết hôm nay thật kỳ lạ." },
  { "chinese": "骑", "pinyin": "qí", "vietnamese": "cưỡi (xe, ngựa)", "example": "我会骑自行车。", "example_vi": "Tôi biết đi xe đạp." },
  { "chinese": "起飞", "pinyin": "qǐfēi", "vietnamese": "cất cánh", "example": "飞机马上就要起飞了。", "example_vi": "Máy bay sắp cất cánh rồi." },
  { "chinese": "清楚", "pinyin": "qīngchu", "vietnamese": "rõ ràng", "example": "我说的话你听清楚了吗？", "example_vi": "Bạn đã nghe rõ những gì tôi nói chưa?" },
  { "chinese": "秋", "pinyin": "qiū", "vietnamese": "mùa thu", "example": "秋天是旅游的好季节。", "example_vi": "Mùa thu là mùa du lịch đẹp." },
  { "chinese": "裙子", "pinyin": "qúnzi", "vietnamese": "váy", "example": "这条裙子很漂亮。", "example_vi": "Chiếc váy này rất đẹp." },
  { "chinese": "然后", "pinyin": "ránhòu", "vietnamese": "sau đó", "example": "我先吃饭，然后去看电影。", "example_vi": "Tôi ăn cơm trước, sau đó đi xem phim." },
  { "chinese": "热情", "pinyin": "rèqíng", "vietnamese": "nhiệt tình", "example": "他是一个很热情的人。", "example_vi": "Anh ấy là một người rất nhiệt tình." },
  { "chinese": "认为", "pinyin": "rènwéi", "vietnamese": "cho rằng", "example": "我认为这个计划很好。", "example_vi": "Tôi cho rằng kế hoạch này rất tốt." },
  { "chinese": "认真", "pinyin": "rènzhēn", "vietnamese": "chăm chỉ, nghiêm túc", "example": "他学习很认真。", "example_vi": "Anh ấy học rất chăm chỉ." },
  { "chinese": "容易", "pinyin": "róngyì", "vietnamese": "dễ dàng", "example": "这个问题很容易回答。", "example_vi": "Vấn đề này rất dễ trả lời." },
  { "chinese": "如果", "pinyin": "rúguǒ", "vietnamese": "nếu", "example": "如果明天不下雨，我们就去公园。", "example_vi": "Nếu ngày mai không mưa, chúng ta sẽ đi công viên." },
  { "chinese": "伞", "pinyin": "sǎn", "vietnamese": "ô, dù", "example": "外面下雨了，记得带伞。", "example_vi": "Bên ngoài trời mưa rồi, nhớ mang ô." },
  { "chinese": "上网", "pinyin": "shàng wǎng", "vietnamese": "lên mạng", "example": "我每天晚上都上网看新闻。", "example_vi": "Mỗi tối tôi đều lên mạng xem tin tức." },
  { "chinese": "声音", "pinyin": "shēngyīn", "vietnamese": "âm thanh", "example": "你听到了什么声音？", "example_vi": "Bạn đã nghe thấy âm thanh gì?" },
  { "chinese": "生气", "pinyin": "shēngqì", "vietnamese": "tức giận", "example": "别生气了，是我不对。", "example_vi": "Đừng giận nữa, là tôi sai." },
  { "chinese": "世界", "pinyin": "shìjiè", "vietnamese": "thế giới", "example": "这个世界很大。", "example_vi": "Thế giới này rất lớn." },
  { "chinese": "瘦", "pinyin": "shòu", "vietnamese": "gầy", "example": "她比以前瘦了很多。", "example_vi": "Cô ấy gầy hơn trước rất nhiều." },
  { "chinese": "舒服", "pinyin": "shūfu", "vietnamese": "thoải mái", "example": "今天天气很好，很舒服。", "example_vi": "Thời tiết hôm nay rất đẹp, rất dễ chịu." },
  { "chinese": "树", "pinyin": "shù", "vietnamese": "cây", "example": "公园里有很多高大的树。", "example_vi": "Trong công viên có rất nhiều cây cao lớn." },
  { "chinese": "刷牙", "pinyin": "shuā yá", "vietnamese": "đánh răng", "example": "睡觉前要刷牙。", "example_vi": "Trước khi đi ngủ phải đánh răng." },
  { "chinese": "双", "pinyin": "shuāng", "vietnamese": "đôi, cặp", "example": "我买了一双新鞋。", "example_vi": "Tôi đã mua một đôi giày mới." },
  { "chinese": "水平", "pinyin": "shuǐpíng", "vietnamese": "trình độ", "example": "他的汉语水平很高。", "example_vi": "Trình độ tiếng Trung của anh ấy rất cao." },
  { "chinese": "司机", "pinyin": "sījī", "vietnamese": "tài xế", "example": "司机先生，请在这里停车。", "example_vi": "Bác tài, xin hãy dừng xe ở đây." },
  { "chinese": "太阳", "pinyin": "tàiyáng", "vietnamese": "mặt trời", "example": "今天的太阳很好。", "example_vi": "Nắng hôm nay rất đẹp." },
  { "chinese": "糖", "pinyin": "táng", "vietnamese": "kẹo, đường", "example": "我喜欢吃糖。", "example_vi": "Tôi thích ăn kẹo." },
  { "chinese": "特别", "pinyin": "tèbié", "vietnamese": "đặc biệt", "example": "这件礼物很特别。", "example_vi": "Món quà này rất đặc biệt." },
  { "chinese": "疼", "pinyin": "téng", "vietnamese": "đau", "example": "我的头很疼。", "example_vi": "Đầu của tôi rất đau." },
  { "chinese": "提高", "pinyin": "tígāo", "vietnamese": "nâng cao", "example": "我们应该努力提高自己的水平。", "example_vi": "Chúng ta nên nỗ lực nâng cao trình độ của bản thân." },
  { "chinese": "体育", "pinyin": "tǐyù", "vietnamese": "thể dục, thể thao", "example": "我最喜欢上体育课。", "example_vi": "Tôi thích nhất là giờ thể dục." },
  { "chinese": "天空", "pinyin": "tiānkōng", "vietnamese": "bầu trời", "example": "天空中有几朵白云。", "example_vi": "Trên bầu trời có vài đám mây trắng." },
  { "chinese": "条", "pinyin": "tiáo", "vietnamese": "lượng từ (vật dài, con vật nhỏ, đường, sông...)", "example": "这条鱼很大。", "example_vi": "Con cá này rất to." },
  { "chinese": "同事", "pinyin": "tóngshì", "vietnamese": "đồng nghiệp", "example": "我和我的同事关系很好。", "example_vi": "Mối quan hệ giữa tôi và đồng nghiệp rất tốt." },
  { "chinese": "同意", "pinyin": "tóngyì", "vietnamese": "đồng ý", "example": "我同意你的看法。", "example_vi": "Tôi đồng ý với quan điểm của bạn." },
  { "chinese": "头发", "pinyin": "tóufa", "vietnamese": "tóc", "example": "她的头发很长。", "example_vi": "Tóc của cô ấy rất dài." },
  { "chinese": "突然", "pinyin": "tūrán", "vietnamese": "đột nhiên", "example": "天突然下起了大雨。", "example_vi": "Trời đột nhiên đổ mưa to." },
  { "chinese": "图书馆", "pinyin": "túshūguǎn", "vietnamese": "thư viện", "example": "我经常去图书馆看书。", "example_vi": "Tôi thường xuyên đến thư viện đọc sách." },
  { "chinese": "腿", "pinyin": "tuǐ", "vietnamese": "chân (bộ phận cơ thể)", "example": "他的腿受伤了。", "example_vi": "Chân của anh ấy bị thương rồi." },
  { "chinese": "完成", "pinyin": "wánchéng", "vietnamese": "hoàn thành", "example": "你完成今天的作业了吗？", "example_vi": "Bạn đã hoàn thành bài tập hôm nay chưa?" },
  { "chinese": "碗", "pinyin": "wǎn", "vietnamese": "cái bát", "example": "请给我一个碗。", "example_vi": "Làm ơn cho tôi một cái bát." },
  { "chinese": "万", "pinyin": "wàn", "vietnamese": "mười nghìn", "example": "这本书有十万字。", "example_vi": "Cuốn sách này có mười vạn chữ." },
  { "chinese": "忘记", "pinyin": "wàngjì", "vietnamese": "quên", "example": "我忘记带钥匙了。", "example_vi": "Tôi quên mang chìa khóa rồi." },
  { "chinese": "为了", "pinyin": "wèile", "vietnamese": "để, vì", "example": "为了健康，我们应该多运动。", "example_vi": "Vì sức khỏe, chúng ta nên vận động nhiều hơn." },
  { "chinese": "位", "pinyin": "wèi", "vietnamese": "vị, ngài (lượng từ lịch sự)", "example": "请问您是哪位？", "example_vi": "Xin hỏi ngài là vị nào?" },
  { "chinese": "文化", "pinyin": "wénhuà", "vietnamese": "văn hóa", "example": "每个国家都有自己的文化。", "example_vi": "Mỗi quốc gia đều có nền văn hóa của riêng mình." },
  { "chinese": "西", "pinyin": "xī", "vietnamese": "hướng Tây", "example": "太阳从西边落下。", "example_vi": "Mặt trời lặn ở hướng Tây." },
  { "chinese": "洗手间", "pinyin": "xǐshǒujiān", "vietnamese": "nhà vệ sinh", "example": "请问洗手间在哪里？", "example_vi": "Xin hỏi nhà vệ sinh ở đâu?" },
  { "chinese": "洗澡", "pinyin": "xǐzǎo", "vietnamese": "tắm", "example": "我每天晚上都洗澡。", "example_vi": "Mỗi tối tôi đều tắm." },
  { "chinese": "夏", "pinyin": "xià", "vietnamese": "mùa hè", "example": "夏天天气很热。", "example_vi": "Mùa hè thời tiết rất nóng." },
  { "chinese": "先", "pinyin": "xiān", "vietnamese": "trước tiên", "example": "你先走吧，我等一下。", "example_vi": "Bạn đi trước đi, tôi đợi một lát." },
  { "chinese": "相同", "pinyin": "xiāngtóng", "vietnamese": "giống nhau", "example": "我们的爱好相同。", "example_vi": "Sở thích của chúng ta giống nhau." },
  { "chinese": "相信", "pinyin": "xiāngxìn", "vietnamese": "tin tưởng", "example": "我相信你一定能成功。", "example_vi": "Tôi tin rằng bạn nhất định sẽ thành công." },
  { "chinese": "像", "pinyin": "xiàng", "vietnamese": "giống như", "example": "他长得像他爸爸。", "example_vi": "Nó trông giống bố nó." },
  { "chinese": "向", "pinyin": "xiàng", "vietnamese": "hướng về", "example": "他向我走了过来。", "example_vi": "Anh ấy đi về phía tôi." },
  { "chinese": "小心", "pinyin": "xiǎoxīn", "vietnamese": "cẩn thận", "example": "过马路要小心。", "example_vi": "Qua đường phải cẩn thận." },
  { "chinese": "校长", "pinyin": "xiàozhǎng", "vietnamese": "hiệu trưởng", "example": "校长在办公室里。", "example_vi": "Hiệu trưởng đang ở trong văn phòng." },
  { "chinese": "新鲜", "pinyin": "xīnxiān", "vietnamese": "tươi mới", "example": "这些水果很新鲜。", "example_vi": "Những loại trái cây này rất tươi." },
  { "chinese": "信", "pinyin": "xìn", "vietnamese": "thư", "example": "我收到了朋友的信。", "example_vi": "Tôi đã nhận được thư của bạn." },
  { "chinese": "行李箱", "pinyin": "xínglixiāng", "vietnamese": "vali", "example": "我的行李箱太重了。", "example_vi": "Vali của tôi nặng quá." },
  { "chinese": "熊猫", "pinyin": "xióngmāo", "vietnamese": "gấu trúc", "example": "熊猫是中国的国宝。", "example_vi": "Gấu trúc là quốc bảo của Trung Quốc." },
  { "chinese": "需要", "pinyin": "xūyào", "vietnamese": "cần", "example": "我需要你的帮助。", "example_vi": "Tôi cần sự giúp đỡ của bạn." },
  { "chinese": "选择", "pinyin": "xuǎnzé", "vietnamese": "lựa chọn", "example": "这是你自己的选择。", "example_vi": "Đây là sự lựa chọn của chính bạn." },
  { "chinese": "要求", "pinyin": "yāoqiú", "vietnamese": "yêu cầu", "example": "老师对我们的要求很高。", "example_vi": "Yêu cầu của giáo viên đối với chúng tôi rất cao." },
  { "chinese": "一般", "pinyin": "yìbān", "vietnamese": "thông thường", "example": "我一般早上七点起床。", "example_vi": "Tôi thường thức dậy lúc bảy giờ sáng." },
  { "chinese": "一边", "pinyin": "yìbiān", "vietnamese": "vừa... vừa...", "example": "他喜欢一边听音乐一边做作业。", "example_vi": "Cậu ấy thích vừa nghe nhạc vừa làm bài tập." },
  { "chinese": "一定", "pinyin": "yídìng", "vietnamese": "nhất định", "example": "我明天一定会来。", "example_vi": "Ngày mai tôi nhất định sẽ đến." },
  { "chinese": "一共", "pinyin": "yígòng", "vietnamese": "tổng cộng", "example": "这些东西一共多少钱？", "example_vi": "Tổng cộng những thứ này bao nhiêu tiền?" },
  { "chinese": "一会儿", "pinyin": "yíhuìr", "vietnamese": "một lúc", "example": "请等一会儿。", "example_vi": "Xin hãy đợi một lát." },
  { "chinese": "一样", "pinyin": "yíyàng", "vietnamese": "giống nhau", "example": "这两个苹果看起来一样。", "example_vi": "Hai quả táo này trông giống nhau." },
  { "chinese": "以前", "pinyin": "yǐqián", "vietnamese": "trước đây", "example": "我以前住在这里。", "example_vi": "Trước đây tôi sống ở đây." },
  { "chinese": "以为", "pinyin": "yǐwéi", "vietnamese": "tưởng rằng", "example": "我以为你今天不来了。", "example_vi": "Tôi đã tưởng rằng hôm nay bạn không đến." },
  { "chinese": "一直", "pinyin": "yìzhí", "vietnamese": "luôn luôn, suốt", "example": "我一直在等你。", "example_vi": "Tôi vẫn luôn đợi bạn." },
  { "chinese": "银行", "pinyin": "yínháng", "vietnamese": "ngân hàng", "example": "我要去银行取钱。", "example_vi": "Tôi phải đến ngân hàng rút tiền." },
  { "chinese": "应该", "pinyin": "yīnggāi", "vietnamese": "nên", "example": "我们应该互相帮助。", "example_vi": "Chúng ta nên giúp đỡ lẫn nhau." },
  { "chinese": "影响", "pinyin": "yǐngxiǎng", "vietnamese": "ảnh hưởng", "example": "请不要影响别人学习。", "example_vi": "Xin đừng làm ảnh hưởng đến việc học của người khác." },
  { "chinese": "用", "pinyin": "yòng", "vietnamese": "dùng", "example": "你可以用我的电脑。", "example_vi": "Bạn có thể dùng máy tính của tôi." },
  { "chinese": "游戏", "pinyin": "yóuxì", "vietnamese": "trò chơi", "example": "孩子们喜欢玩游戏。", "example_vi": "Trẻ con thích chơi trò chơi." },
  { "chinese": "有名", "pinyin": "yǒumíng", "vietnamese": "nổi tiếng", "example": "他是一位有名的作家。", "example_vi": "Ông ấy là một nhà văn nổi tiếng." },
  { "chinese": "愿意", "pinyin": "yuànyì", "vietnamese": "sẵn lòng", "example": "你愿意帮助我吗？", "example_vi": "Bạn có sẵn lòng giúp tôi không?" },
  { "chinese": "月亮", "pinyin": "yuèliang", "vietnamese": "mặt trăng", "example": "今晚的月亮真圆。", "example_vi": "Mặt trăng tối nay thật tròn." },
  { "chinese": "越", "pinyin": "yuè", "vietnamese": "càng", "example": "他越说越激动。", "example_vi": "Anh ấy càng nói càng kích động." },
  { "chinese": "云", "pinyin": "yún", "vietnamese": "mây", "example": "天上的云真白。", "example_vi": "Mây trên trời thật trắng." },
  { "chinese": "站", "pinyin": "zhàn", "vietnamese": "trạm, đứng", "example": "请在这里排队站好。", "example_vi": "Xin hãy xếp hàng đứng ngay ngắn ở đây." },
  { "chinese": "照顾", "pinyin": "zhàogù", "vietnamese": "chăm sóc", "example": "请帮我照顾一下我的小狗。", "example_vi": "Làm ơn chăm sóc giúp tôi con chó nhỏ." },
  { "chinese": "照片", "pinyin": "zhàopiàn", "vietnamese": "bức ảnh", "example": "这张照片拍得很好看。", "example_vi": "Bức ảnh này chụp rất đẹp." },
  { "chinese": "照相机", "pinyin": "zhàoxiàngjī", "vietnamese": "máy ảnh", "example": "我新买了一台照相机。", "example_vi": "Tôi mới mua một cái máy ảnh." },
  { "chinese": "只", "pinyin": "zhǐ", "vietnamese": "chỉ, lượng từ cho động vật", "example": "我只有十块钱了。", "example_vi": "Tôi chỉ còn có mười đồng thôi." },
  { "chinese": "中间", "pinyin": "zhōngjiān", "vietnamese": "ở giữa", "example": "我就站在他们中间。", "example_vi": "Tôi đang đứng giữa họ." },
  { "chinese": "终于", "pinyin": "zhōngyú", "vietnamese": "cuối cùng", "example": "我们终于完成了这个任务。", "example_vi": "Cuối cùng chúng tôi đã hoàn thành nhiệm vụ này." },
  { "chinese": "重要", "pinyin": "zhòngyào", "vietnamese": "quan trọng", "example": "这是一个非常重要的会议。", "example_vi": "Đây là một cuộc họp rất quan trọng." },
  { "chinese": "周末", "pinyin": "zhōumò", "vietnamese": "cuối tuần", "example": "你这个周末有什么计划？", "example_vi": "Cuối tuần này bạn có kế hoạch gì không?" },
  { "chinese": "主要", "pinyin": "zhǔyào", "vietnamese": "chủ yếu", "example": "今天会议的主要内容是什么？", "example_vi": "Nội dung chính của cuộc họp hôm nay là gì?" },
  { "chinese": "注意", "pinyin": "zhùyì", "vietnamese": "chú ý", "example": "请注意安全。", "example_vi": "Xin hãy chú ý an toàn." },
  { "chinese": "字典", "pinyin": "zìdiǎn", "vietnamese": "từ điển", "example": "遇到不认识的字，可以查字典。", "example_vi": "Gặp chữ không biết, có thể tra từ điển." },
  { "chinese": "自己", "pinyin": "zìjǐ", "vietnamese": "bản thân", "example": "你应该相信自己。", "example_vi": "Bạn nên tin tưởng vào bản thân." },
  { "chinese": "总是", "pinyin": "zǒngshì", "vietnamese": "luôn luôn", "example": "他总是迟到。", "example_vi": "Anh ta luôn luôn đến muộn." },
  { "chinese": "最后", "pinyin": "zuìhòu", "vietnamese": "cuối cùng", "example": "我们最后还是决定不去。", "example_vi": "Cuối cùng chúng tôi vẫn quyết định không đi." },
  { "chinese": "最近", "pinyin": "zuìjìn", "vietnamese": "gần đây", "example": "你最近忙吗？", "example_vi": "Dạo này bạn có bận không?" },
  { "chinese": "作业", "pinyin": "zuòyè", "vietnamese": "bài tập", "example": "今天的作业你做完了吗？", "example_vi": "Bạn đã làm xong bài tập hôm nay chưa?" },
  { "chinese": "作用", "pinyin": "zuòyòng", "vietnamese": "tác dụng", "example": "这种药有什么作用？", "example_vi": "Loại thuốc này có tác dụng gì?" }
];
